### ISSUE TITLE
Question: How to configure Sleuth with Zipkin over RabbitMQ

### ISSUE THREAD

**Issue by robachmann** [spring-cloud/spring-cloud-sleuth#1004]
I would like to send spans through a RabbitMQ to Zipkin. Therefore I use the Zipkin distribution jar (`zipkin-server-2.8.4-exec.jar`) and deploy it to Cloud Foundry with these manifest arguments:
```
  services:
    - elasticsearch-zipkin
    - rabbitmq-zipkin
  env:
    RABBIT_URI: ${vcap.services.rabbitmq-zipkin.credentials.uri}
```
In the _producer_ app with sleuth, I add the following dependencies:
```
    compile('org.springframework.boot:spring-boot-starter-amqp')
    compile('org.springframework.cloud:spring-cloud-starter-zipkin')
    compile('org.springframework.amqp:spring-rabbit')
```
Note that the first one is used to send other messages to another application through RMQ and the last one is just to debug as it's included in the first one. 

The used Cloud and Boot versions are `Finchley.RC2` and `2.0.2.RELEASE`.

Finally, I add the following properties to `application.yml`:
```
  sleuth:
    sampler:
      probability: 1.0
    messaging:
      enabled: true
      rabbit:
        enabled: true
        remote-service-name: rabbitmq-zipkin
  zipkin:
    sender:
      type: rabbit
    service:
      name: myapp
```
_Note the remote-service-name corresponds to the service name in Cloud Foundry._

When both apps are started, I see that zipkin-server auto-creates the queue named 'zipkin'. Also, log-files from the sleuth-app look like this:
```
2018-06-07T15:58:11.42+0200 [APP/PROC/WEB/0] OUT 2018-06-07 13:58:11.421  INFO [myapp,f21e0ded48255245,f21e0ded48255245,true] 8 --- [pool-5-thread-1] o.s.a.r.c.CachingConnectionFactory       : Created new connection: SpringAMQP#404913f6:0/SimpleConnection@6beb433f [delegate=amqp://Y342KiwcvGv34ruq@10.10.22.22:5672/9437a9a6-597c-4e94-b4d7-6cb85a2ab647, localPort= 53618]
```
Unfortunately, I never see the span written to RMQ, the queue named 'zipkin' remains empty.

Is there anything I missed to configure? What are possible ways to debug it?
