### ISSUE TITLE
steam pooler not work

### ISSUE THREAD

**Issue by zhongyusimon** [spring-cloud/spring-cloud-sleuth#1025]
Bug report

I try to use kafka stream for zipkin, and config as below, but it donsnt work. then I read the source, found that in class **org.springframework.cloud.sleuth.stream.StreamSpanReporter** spanToReport was repored, but never polled. Then I write a main function and it worked fine.

spring-cloud-version: Edgware.SR3
spring boot version: 1.5.13.RELEASE
**config**
```xml
<dependencies>
        <dependency>
            <groupId>org.springframework.cloud</groupId>
            <artifactId>spring-cloud-sleuth-zipkin-stream</artifactId>
        </dependency>
        <dependency>
            <groupId>org.springframework.boot</groupId>
            <artifactId>spring-boot-starter-web</artifactId>
        </dependency>
        <dependency>
            <groupId>org.springframework.cloud</groupId>
            <artifactId>spring-cloud-starter-stream-kafka</artifactId>
        </dependency>
        <dependency>
            <groupId>org.springframework.cloud</groupId>
            <artifactId>spring-cloud-sleuth-stream</artifactId>
        </dependency>
    </dependencies>
```

```yaml
spring:
  application:
    name: test-kafka
  profiles: dev
  http:
    encoding:
      charset: UTF-8
      enabled: true
      force: true
server:
  port: 8090
  tomcat:
    uri-encoding: UTF-8
eureka:
  client:
    enabled: false

```

```
spring.cloud.stream.kafka.binder.brokers=localhost:9092
spring.cloud.stream.kafka.binder.zk-nodes=localhost:2181
spring.cloud.stream.kafka.binder.minPartitionCount=1
spring.cloud.stream.kafka.binder.autoCreateTopics=true
spring.cloud.stream.kafka.binder.autoAddPartitions=true

spring.sleuth.enabled=true
spring.sleuth.sampler.percentage=1.0

spring.application.name=test-kafka
spring.zipkin.service.name=test-kafka-z

```

**sample i write**
```java
@InboundChannelAdapter(value = OrderStatusChangeChannel.STATUS_CHANGE_PRODUCER, poller = @Poller(fixedDelay = "1000"))
    public String foo() {
        System.out.print("foo\n");
        return "foo";
    }
```
