### ISSUE TITLE
Sleuth using same traceId for all the messages received from websocket client

### ISSUE THREAD

**Issue by krmanish007** [spring-cloud/spring-cloud-sleuth#1058]
Hi,

I am integrating sleuth in a project where we receive the message from WebSocket and persist it into Kafka. When we start the project, it's all working fine, but after sometime sleuth starts printing the same traceId for all the various messages received from WebSocket. It seems so far single thread is receiving all the messages, it works fine but when some other thread from the scheduler prints some log with some traceId, that traceId becomes a default for all the future log, but the behavior is not consistent.

I have created a sample project with various limited to reflect the issue at https://github.com/krmanish007/SleuthtestApplication

**Comment by zhongyusimon** [comment]
I've had this problem. and more is happening when use docker. so I think it's probably a random question,  using random.nextInt or random.nextLong.

**Comment by adriancole** [comment]
more often problems like this are about context leak and not about random number choosing same value

**Comment by zhongyusimon** [comment]
> more often problems like this are about context leak and not about random number choosing same value

you mean it may occurs while a thread don't release the ThreadLocal param of sleuth? This could indeed happen, I will check it.

**Comment by adriancole** [comment]
yeah or if thread local is inheritable (like a connection pool grows) this can cause a trace ID to stick around more than helpful.

**Comment by zhongyusimon** [comment]
I found that below massive network pressure, come out warning log. I have tried to reproduce on my dev-env but it can't appear. 
`2018-11-01 11:28:53,022 [http-nio-10086-exec-48] [WARN ] [5bda6d7afee5e7089fa08d02b976c8e0,ce7ba14edd62221f,true]o.s.c.s.u.ExceptionUtils Tried to detach trace span but it is not the current span: [Trace: 5bda6d7afee5e7089fa08d02b976c8e0, Span: f91eaa98cd78386f, Parent: 7e5532e8e8b9727c, exportable:true]. You may have forgotten to close or detach [Trace: 5bda6d7afee5e7089fa08d02b976c8e0, Span: ce7ba14edd62221f, Parent: f91eaa98cd78386f, exportable:true]`

**Comment by zhongyusimon** [comment]
`
<dependencyManagement>
        <dependencies>
            <dependency>
                <groupId>org.springframework.cloud</groupId>
                <artifactId>spring-cloud-dependencies</artifactId>
                <version>Edgware.SR3</version>
                <type>pom</type>
                <scope>import</scope>
            </dependency>
            <dependency>
                <groupId>org.springframework.boot</groupId>
                <artifactId>spring-boot-dependencies</artifactId>
                <version>1.5.13.RELEASE</version>
                <type>pom</type>
                <scope>import</scope>
            </dependency>
       </dependencies>
   </dependencyManagement>
       <dependency>
            <groupId>org.springframework.cloud</groupId>
            <artifactId>spring-cloud-starter-zipkin</artifactId>
        </dependency>
        <dependency>
            <groupId>org.springframework.kafka</groupId>
            <artifactId>spring-kafka</artifactId>
        </dependency>
`

zipkin properties
`
spring.kafka.bootstrapServers=192.168.11.11:9092
spring.zipkin.sender.type=KAFKA

spring.sleuth.enabled=true
spring.sleuth.sampler.percentage=1.0

spring.sleuth.trace-id128=true

spring.sleuth.scheduled.enabled=false
`

**Comment by zhongyusimon** [comment]
```yml
hystrix:
  command:
    default:
      circuitBreaker:
        enabled: false
        sleepWindowInMilliseconds: 5000
        requestVolumeThreshold: 15
        errorThresholdPercentage: 50
      execution:
        isolation:
          strategy: SEMAPHORE
          thread:
            timeoutInMilliseconds: 80000
            ribbon:
              ReadTimeout: 30000
              ConnectTimeout: 30000
          semaphore:
            maxConcurrentRequests: 100000
      fallback:
        isolation:
          semaphore:
            maxConcurrentRequests: 2000
  threadpool:
    default:
      coreSize: 200
      maxQueueSize: 10000
      queueSizeRejectionThreshold: 1000
```
