### ISSUE TITLE
The tracing chain is not complete when Spring Cloud Zuul enable okhttp3

### ISSUE THREAD

**Issue by weiwunb** [spring-cloud/spring-cloud-sleuth#1142]
Question

The tracing chain is not complete when Spring Cloud Zuul enable okhttp3.

- spring-boot.version: `2.0.3.RELEASE`
- spring-cloud.version: `Finchley.RELEASE`

In our test scenario, we call the `test-demo-api` through spring cloud zuul and want to get the tracing data from zipkin. Here is the zipkin configuration:
```
spring:
  application:
    name: ccf-gateway-app
  zipkin:
    enabled: true
    sender:
      type: web
    base-url: http://xxx.xxx.xxx.xxx:9411
  sleuth:
    sampler:
      probability: 1.0
```

---

Here is the tracing chain when we use **apache http client**:

```
application.yaml
--------
ribbon:
  ReadTimeout: 2000
  ConnectTimeout: 1000
  httpclient:
    enabled: true
  okhttp:
    enabled: false
```

<img src="https://user-images.githubusercontent.com/28476370/48910736-ae8b8e80-eeab-11e8-95b5-d7eb0f61b046.png">

---

Here is the tracing chain when we use **okhttp3**:

```
pom.xml
---
<dependency>
    <groupId>com.squareup.okhttp3</groupId>
    <artifactId>okhttp</artifactId>
</dependency>
<dependency>
    <groupId>org.springframework.cloud</groupId>
    <artifactId>spring-cloud-starter-netflix-zuul</artifactId>
</dependency>
<dependency>
    <groupId>org.springframework.cloud</groupId>
    <artifactId>spring-cloud-starter-zipkin</artifactId>
</dependency>
```

```
application.yaml
--------
ribbon:
  ReadTimeout: 2000
  ConnectTimeout: 1000
  httpclient:
    enabled: false
  okhttp:
    enabled: true
```

<img width="792" alt="wechatimg814" src="https://user-images.githubusercontent.com/28476370/48910929-3c677980-eeac-11e8-86e4-c3268c441558.png">

---

As you see, the tracing data miss the test-demo-api part when we enable okhttp3.

We found this link [brave-instrumentation-okhttp3](https://github.com/openzipkin/brave/tree/master/instrumentation/okhttp3), is this a bug in `spring-cloud-starter-zipkin`?
