### ISSUE TITLE
Regression: server.servlet.context-path skips all endoints

### ISSUE THREAD

**Issue by melloware** [spring-cloud/spring-cloud-sleuth#1146]
**Sprint Boot:** 2.1.0
**Spring Cloud:** Greenwich.M3

Regression from this issue: https://github.com/spring-cloud/spring-cloud-sleuth/issues/971

If you include a servlet context path like this:
```yaml
server:
  port: 8080
  servlet:
      context-path: /melloware/
```

All endpoints are skipped and no Zipkin messages are sent.  If you remove the context-path then all Zipkin messages are sent and received.
```yaml
server:
  port: 8080
```
