### ISSUE TITLE
zuul with numerous request and  sleuth generate duplicate traceid?

### ISSUE THREAD

**Issue by yugj** [spring-cloud/spring-cloud-sleuth#1159]
hi,

i use slueth, hystrix,ribbon in my zuul proxy application

Spirngclond  version: Edgware.SR5

Springboot version:1.5.7.RELEASE

i see so many request with same traceid, and it have a same thread_name (my test envirement does not occurred, but my product envirement occurred)

Time 	HOSTNAME  	X-B3-TraceId  	thread_name  
December 13th 2018, 09:41:26.950	FJXM-DM-Dmz-VM6-041	5536c838f82629e7	http-nio-18001-exec-91
December 13th 2018, 09:41:24.168	FJXM-DM-Dmz-VM6-041	5536c838f82629e7	http-nio-18001-exec-91
December 13th 2018, 09:41:21.473	FJXM-DM-Dmz-VM6-041	5536c838f82629e7	http-nio-18001-exec-91
December 13th 2018, 09:41:21.459	FJXM-DM-Dmz-VM6-041	5536c838f82629e7	http-nio-18001-exec-91
December 13th 2018, 09:41:19.046	FJXM-DM-Dmz-VM6-041	5536c838f82629e7	http-nio-18001-exec-91
December 13th 2018, 09:41:16.508	FJXM-DM-Dmz-VM6-041	5536c838f82629e7	http-nio-18001-exec-91
December 13th 2018, 09:41:16.390	FJXM-DM-Dmz-VM6-041	5536c838f82629e7	http-nio-18001-exec-91
December 13th 2018, 09:41:14.113	FJXM-DM-Dmz-VM6-041	5536c838f82629e7	http-nio-18001-exec-91
December 13th 2018, 09:41:11.840	FJXM-DM-Dmz-VM6-041	5536c838f82629e7	http-nio-18001-exec-91
……..

i search the early issue :

https://github.com/spring-cloud/spring-cloud-sleuth/issues/634

https://github.com/spring-cloud/spring-cloud-sleuth/issues/728

https://github.com/spring-cloud/spring-cloud-sleuth/issues/849

i have upgrade springclound from Dalston.SR4 to Edgware.SR3; Edgware.SR3 to Edgware.SR5

And the duplicate traceid still occurred,i really need some help :)

this is the traceid:5536c838f82629e7 first occur

December 11th 2018, 13:22:26.093	FJXM-DM-Dmz-VM6-041	**Tried to close span but it is not the current span: [Trace: 5536c838f82629e7, Span: 5536c838f82629e7, Parent: null, exportable:false].  You may have forgotten to close or detach [Trace: 5536c838f82629e7, Span: 40471995be02b52c, Parent: 5536c838f82629e7, exportable:false]	http-nio-18001-exec-91**
December 11th 2018, 13:22:26.092	FJXM-DM-Dmz-VM6-041	sys error,http status:500,originUri:/client/sop	http-nio-18001-exec-91
December 11th 2018, 13:22:26.091	FJXM-DM-Dmz-VM6-041	Error during filtering	http-nio-18001-exec-91
December 11th 2018, 13:22:26.091	FJXM-DM-Dmz-VM6-041	**Premature end of chunk coded message body: closing chunk expected	http-nio-18001-exec-91**
December 11th 2018, 13:22:26.091	FJXM-DM-Dmz-VM6-041	AccessErrorFilter : Premature end of chunk coded message body: closing chunk expected	http-nio-18001-exec-91
December 11th 2018, 13:22:25.926	FJXM-DM-Dmz-VM6-041	zuul request xxx 

My kibana show the count of duplicate traceid,it happens in 2 node of my cluster,and have the same thread_name,i use md5sum to sum my jar files and it is the same (my zuul application deploy with jar file)

X-B3-TraceId.keyword: Descending 	Count 
97c56d437ede71e4	211,695
5536c838f82629e7	208,482
7996e6c16710481e  	12
0bb9d9e2441b8381	11
5c77a477721af529	11
a7f7884e47f4820b	11
c1942b6ed9e918e7	11
d704ec8994269237	11
f0bf7c3d20c8bdcb	11
06079d7a93fc1586	10

My application.yml (main properites)

```yaml
server:
  port: 18001
  tomcat:
    #default 10000
    max-connections: 10000
    #default 200
    max-threads: 2000

spring:
  profiles:
    active: @profile.id@
  application:
    name: ms-zuul
    # HTTP ENCODING
  http:
    encoding.charset: UTF-8
    encoding.enabled: true
    encoding.force: true
    multipart:
      max-file-size: 104857600

zuul:
  routes:
    sop:
      path: /sop/**
      strip-prefix: false
      serviceId: mg-sop
  max:
    host:
      connections: 60000
  host:
    socket-timeout-millis: 20000
    connect-timeout-millis: 2000
    max-per-route-connections: 1000
    max-total-connections: 1000
  semaphore:
    max-semaphores: 2000
  groovyFiltersPath: /data/groovy/${spring.profiles.active}
hystrix:
  threadpool:
    default:
      coreSize: 500
  command:
    default:
      execution:
        timeout:
          enabled: true
        isolation:
          thread:
            timeoutInMilliseconds: 20000
ribbon:
  MaxConnectionsPerHost: 500
  MaxTotalConnections: 2000
  ReadTimeout: 17000
  ConnectTimeout: 2000
  MaxAutoRetries: 0
  MaxAutoRetriesNextServer: 0
  ServerListRefreshInterval: 10000
  eureka:
    enabled: true

management:
  security:
    enabled: false
  health:
    rabbit:
      enabled: false

log:
  home: /data/logs/${spring.profiles.active}
eureka:
  client:
    healthcheck:
      enabled: true
```

clear  MDC code

```java
@Component
@RefreshScope
public class MDCCleanFilter extends AbstZuulFilter {

    private static final Logger log = LoggerFactory.getLogger(MDCCleanFilter.class);


    @Override
    public String filterType() {
        return FilterConstants.POST_TYPE;
    }

    @Override
    public int filterOrder() {
        return Integer.MAX_VALUE;
    }

    @Override
    public boolean shouldFilter() {
        return true;
    }

    @Override
    public Object run() throws ZuulException {

        if (log.isDebugEnabled()) {
            log.debug("clear mdc");
        }

        MDC.clear();

        return null;
    }
}
```

**i have two question:**

**1,**December 11th 2018, 13:22:26.093	FJXM-DM-Dmz-VM6-041	Tried to close span but it is not the current span: [Trace: 5536c838f82629e7, Span: 5536c838f82629e7, Parent: null, exportable:false].  You may have forgotten to close or detach [Trace: 5536c838f82629e7, Span: 40471995be02b52c, Parent: 5536c838f82629e7, exportable:false]	http-nio-18001-exec-91

Should i close the span manually ？

**2**,what shoud i do to prevent this problem happen again
