### ISSUE TITLE
Set spring.sleuth.sampler.probability to 1.0, no effect

### ISSUE THREAD

**Issue by upcwangying** [spring-cloud/spring-cloud-sleuth#1314]
Spring Cloud： Finchley.RC2

Set spring.sleuth.sampler.probability to 1.0, no effect

**Comment by marcingrzejszczak** [comment]
Please use the latest GA release. RC2 is a release candidate

**Comment by upcwangying** [comment]
Spring Boot: 2.0.6.RELEASE

Spring Cloud：Finchley.SR2

Set spring.sleuth.sampler.probability to 1.0, no effect

pom:
<dependency>
    <groupId>org.springframework.cloud</groupId>
    <artifactId>spring-cloud-starter-zipkin</artifactId>
</dependency>

application.yml:

spring:
  zipkin:
    base-url: http://*.*.*.*:9411
    sender:
      type: web
  sleuth:
    sampler:
      probability: 1.0

logging:
  level:
    org.springframework.cloud.openfeign: debug

**Comment by upcwangying** [comment]
Spring Boot: 2.0.6.RELEASE

Spring Cloud：Finchley.SR2

Set spring.sleuth.sampler.probability to 1.0, no effect

pom
```
<dependency>
    <groupId>org.springframework.cloud</groupId>
    <artifactId>spring-cloud-starter-zipkin</artifactId>
</dependency>
```
application.yml
```
spring:
  zipkin:
    base-url: http://*.*.*.*:9411
    sender:
      type: web
  sleuth:
    sampler:
      probability: 1.0

logging:
  level:
    org.springframework.cloud.openfeign: debug
```
