### ISSUE TITLE
Zipkin server unable to consume span message from kafka

### ISSUE THREAD

**Issue by aniketvsawant** [spring-cloud/spring-cloud-sleuth#1321]
Hi Team,

I have configured my services with sleuth and enabled zipkin sender type as kafka. All the services are able to publish span messages to kafka but zipkin server at other end is not able to consume the messages from kafka. 

Here are my details.

dependencies
```
  compile "io.zipkin.java:zipkin-server:2.12.5"
  compile "io.zipkin.java:zipkin-autoconfigure-ui:2.12.6"
  compile "org.springframework.cloud:spring-cloud-starter-stream-kafka:2.1.0.RELEASE"
``` 

ApplicationClass
```
@SpringBootApplication
@EnableZipkinServer
public class ZipkinServiceApplication {
    @Bean
    ServletWebServerFactory servletWebServerFactory(){
        return new TomcatServletWebServerFactory();
    }

    public static void main( String[] args ) {
        SpringApplication.run(ZipkinServiceApplication.class, args);
    }
}
```

application.properties
```
spring:
  cloud:
    stream:
      kafka:
        binder:
          brokers: localhost:9092
          zkNodes: localhost:2181
```
Am i missing anything ? Zipkin is not able to consume messages from kafka and so tracing information is not showing on zipkin ui.
