### ISSUE TITLE
Exchange settings are supported, when using RabbitMQ

### ISSUE THREAD

**Issue by sdlzhd** [spring-cloud/spring-cloud-sleuth#1405]
I'm using Sleuth to track microservice calls and send these data to RabbitMQ, When I used Zipkin server, everything was fine. There are some questions if I want to use these messages elsewhere. 
Is there a way to specify how Span information is sent to MQ, such as to a direct Exchange?

```yml
spring:
  zipkin:
    rabbitmq:
      exchange:
        name:
        type:
        key:
        ...
```
