### ISSUE TITLE
SleuthKafkaAspect not working

### ISSUE THREAD

**Issue by matus753** [spring-cloud/spring-cloud-sleuth#1426]
I'm using spring version 2.1.7.RELEASE, and i add spring-cloud-starter-sleuth:2.1.0.RELEASE,
after that i enabled aspect by "@EnableAspectJAutoProxy" and add configuration for enabling kafka tracing: `spring.sleuth.messaging.kafka.enabled: true`. When i start my application, TraceMessagingAutoConfiguration is triggered, and it create SleuthKafkaAspect, which should 
wrap producer and consumer factory. But that never hapen, SleuthKafkaAspect is create, but app never reach code in method wrapProducerFactory, it's ignored and only deafault producer withou tracing is created. What am i missing, that this aspect never work for me?

**Comment by marcingrzejszczak** [comment]
Hi! Can you always, before asking a question or posting an issue, try to upgrade to the latest version (e.g. `2.1.2.RELEASE`) and check if the problem still persists?

**Comment by matus753** [comment]
sorry for that, i upgraded to the latest version but ma problem still persist

**Comment by marcingrzejszczak** [comment]
Can you upload a sample that reproduces the problem? I would like to see how you set up the project and how you're using the kafka logic.

**Comment by matus753** [comment]
I am note sure what exactly you mean by sample, so I hope I got it right
my app configuration: 
```
spring:
  sleuth:
    messaging:
      kafka:
        enabled: true
  kafka:
    bootstrap-servers: ${KAFKA_URL}
    producer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
    consumer:
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.apache.kafka.common.serialization.StringDeserializer
  cloud:
    stream:
      bindings:
        input:
          destination: DESTINATION_NAME
          contentType: application/json
          group: GROUP_NAME
          consumer:
            headerMode: raw
        output:
          destination: DESTINATION_NAME
          contentType: application/json
          producer:
            headerMode: raw
```
spring boot main class:
```
@SpringBootApplication
@EnableAspectJAutoProxy
public class MyApplication {

    public static void main(String... args) {
        SpringApplication.run(MyApplication .class, args);
    }
}
```
impl class: 
```
import static org.springframework.cloud.stream.messaging.Sink.INPUT;
import static org.springframework.cloud.stream.messaging.Source.OUTPUT;

import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.cloud.stream.annotation.EnableBinding;
import org.springframework.cloud.stream.annotation.StreamListener;
import org.springframework.cloud.stream.messaging.Processor;
import org.springframework.cloud.stream.messaging.Sink;
import org.springframework.integration.support.MessageBuilder;
import org.springframework.messaging.Message;
import org.springframework.messaging.handler.annotation.Payload;
import org.springframework.messaging.handler.annotation.SendTo;

@Slf4j
@EnableBinding(Processor.class)
public class MyMapper {

    @StreamListener(INPUT)
    @SendTo(OUTPUT)
    public Message<Object> process(@Payload Object message) {
       //some code here to convert data
       return MessageBuilder
                    .withPayload(data)
                    .setHeader(Constants.MESSAGE_KEY_OUTGOING, key)
                    .build();
    }
}
```
