### ISSUE TITLE
Root Spans in Spring-Cloud-Gateway always named based on an "/" request

### ISSUE THREAD

**Issue by Laures** [spring-cloud/spring-cloud-sleuth#1535]
**Describe the bug**
when integrating sleuth into spring-cloud-gateway every request creates two spans. the root span (created by `httpclientbeanpostprocessor`) is always a request aggainst "/". No matter what the actual request looks like. The second span is based on the actual request and created by `TraceWebFilter`

**Sample**
Create a basic project with spring-initializer containing spring-cloud-gateway, sleuth and a reporter/sender of your choice (i used both zipkin and google compute for testing). Configure a route and make a request.

````
spring:
  cloud:
    gateway:
      routes:
        - id: method_route
          uri: https://example.org/2
          predicates:
            - Path=/**
````

The exact trace content depends on your dependencies. Zipkin names the root span "GET". GCP names it "/". both a not usable.

**Comment by marcingrzejszczak** [comment]
Which versions have you been using?

**Comment by Laures** [comment]
My sample project is based on spring-boot 2.2.4.RELEASE and spring-cloud Hoxton.SR1

that is spring-cloud-starter-sleuth and spring-cloud-starter-gateway 2.2.1.RELEASE

**Comment by marcingrzejszczak** [comment]
In `3.0.0-SNAPSHOT` and the upcoming milestone release we have done a lot of work in making the reactive approach work better with Spring Cloud Sleuth. Since Spring Cloud Gateway is fully reactive, with the following changes you'll be able to speed things up and get consistent results.

Example for the following setup:

```yaml
spring:
  cloud:
    gateway:
      routes:
        - id: method_route
          uri: https://httpbin.org/
          predicates:
            - Path=/httpbin/**
          filters:
            - StripPrefix=1
  sleuth:
    reactor:
      instrumentation-type: manual
```

The trace with the root span clicked

![image](https://user-images.githubusercontent.com/3297437/89551154-e74bd280-d80a-11ea-9e6e-69ff5015ec32.png)

The trace with the client span clicked
![image](https://user-images.githubusercontent.com/3297437/89551067-c97e6d80-d80a-11ea-886b-62bccb580212.png)
