### ISSUE TITLE
Baggage and Propagation keys are not propagating from Spring boot web to kafka 

### ISSUE THREAD

**Issue by Srinivas018** [spring-cloud/spring-cloud-sleuth#1678]
The Baggage and Propagation keys are not propagating from restservice to Kafka listener whereas these are working fine between the microservices. And the infra are: latest stable version of Kafka(2.x),  spring-kafka, spring-boot(2.3.1) and sleuth(2.2.3).

Here is the configuration in both rest and kafka listener
```
spring:
  sleuth:
    baggage-keys:
      - baggage
      - e-xyz-loctran-id
    propagation-keys:
      - x-vcap-request-id
    log.slf4j.whitelisted-mdc-keys:
      - x-vcap-request-id
      - e-xyz-loctran-id
```
**Part of logback_spring.xml from both the components:**
```<property name="CONSOLE_LOG_PATTERN"
              value="%clr(%d{yyyy-MM-dd HH:mm:ss.SSS}){faint} %clr(%5p [${springAppName},%X{x-vcap-request-id:-},%X{user-id:-},%X{e-xyz-loctran-id:-},%X{spanId:-},%X{baggage-TraceId:-}]) />
```
**Log from restservice component**
```2020-07-07 20:22:33.664  INFO [xyz-product-service,ZXC!####,,AS1234,06bf867422a44ec6,]  INFO [,06bf867422a44ec6,06bf867422a44ec6,true] 27316 --- [nio-8080-exec-2] o.a.kafka.common.utils.AppInfoParser     : Kafka commitId: 66563e712b0b9f84
2020-07-07 20:22:33.664  INFO [xyz-product-service,ZXC!####,,AS1234,06bf867422a44ec6,]  INFO [,06bf867422a44ec6,06bf867422a44ec6,true] 27316 --- [nio-8080-exec-2] o.a.kafka.common.utils.AppInfoParser     : Kafka startTimeMs: 1594124553658
2020-07-07 20:22:35.253  INFO [xyz-product-service,,,,,]  INFO [,,,] 27316 --- [ad | producer-1] org.apache.kafka.clients.Metadata        : [Producer clientId=producer-1] Cluster ID: bbLWBsdOcKsdQsSasdfRZLKjWKpwyA
```
**Log from kafka component**
```
2020-07-07 20:22:41.495  INFO [xyz-qos-audit,,,,16eabc20199706a7,]  INFO [,06bf867422a44ec6,16eabc20199706a7,true] 31460 --- [ntainer#0-0-C-1] c.e.n.qosaudit.listener.AuditListener  
```
We can see the traceid propagated successfully but not baggage fields and propagation keys.
