### ISSUE TITLE
using custom headers

### ISSUE THREAD

**Issue by jichu20** [spring-cloud/spring-cloud-sleuth#1754]
Hi.

I want to use sleuth but I can't use the standard tag names 'x-b3-xxx'. I need to be able to use another name, for example traceId, is it possible?

With the following configuration I can propagate my header when it is filled, but if not, how can I generate a value and propagate it?

```
spring:
  application:
    name: poc-logger
  zipkin:
    enabled: false
  sleuth:
    propagation-keys: 
      - traceId
```

I have also tried to use the spring.sleuth.baggage-keys property, but it always includes a prefix, can this be removed?

```
spring:
  application:
    name: poc-logger
  zipkin:
    enabled: false
  sleuth:
    baggage-keys:
      - traceId
```

**Comment by marcingrzejszczak** [comment]
Have you followed the guidelines in the docs (https://docs.spring.io/spring-cloud-sleuth/docs/current/reference/html/#prefixed-fields) for the propagation keys?

**Comment by jichu20** [comment]
Hi. Thank you very much.

I have created a bean in my application with the following content:

```
    @Bean
    Tracing tracing() {

        return Tracing.newBuilder()
                .propagationFactory(ExtraFieldPropagation.newFactoryBuilder(B3Propagation.FACTORY).addField("X-Rho-Traceid").build())
                .build();
    }
```
and a filter with the following content:

```
@Override
    public void doFilter(ServletRequest request, ServletResponse response, FilterChain chain) throws IOException, ServletException {
        Span currentSpan = this.tracer.currentSpan();
        if (currentSpan == null) {
            chain.doFilter(request, response);
            return;
        }

        String xTraceId = ((HttpServletRequest) request).getHeader("X-Rho-Traceid");

        if (StringUtils.isEmpty(xTraceId)) {
            xTraceId = UUID.randomUUID().toString();
            ExtraFieldPropagation.set(currentSpan.context(), "X-Rho-Traceid", xTraceId);
        }
        ((HttpServletResponse) response).addHeader("X-Rho-Traceid", xTraceId);

        MDC.put("X-Rho-Traceid", xTraceId);

        chain.doFilter(request, response);
    }
```

and the config:

```
spring:
  application:
    name: poc-logger
  zipkin:
    enabled: false
``` 
The operation is correct, when I send the header x-rho-traceid with value, it propagates.
When I send it without value, it generates a new value and propagates it.

Another question, ExtraFieldPropagation is deprecated, what is or what will be the way to do this.

Thank you!
