### ISSUE TITLE
basic zipkin - not work

### ISSUE THREAD

**Issue by jichu20** [spring-cloud/spring-cloud-sleuth#1755]
Hi.

Based on the previous [ticket](https://github.com/spring-cloud/spring-cloud-sleuth/issues/1754) I have added zipkin to my project (basic configuration) since my objective is not to send span to zipkin but to generate span in the system sysout.

For this I have added the following configuration to my project.

pom.xml 
```xml
                 <dependency>
			<groupId>org.springframework.cloud</groupId>
			<artifactId>spring-cloud-starter-zipkin</artifactId>
		</dependency>
```

application.yml

```yml
spring:
  application:
    name: poc-logger
  zipkin:
    baseUrl: https://webhook.site/1f66b8f8-d524-4a61-9ef9-b481b3cd53da
    sender:
      type: web
```

But such configuration does not generate any action.

Can you help me.

**Comment by marcingrzejszczak** [comment]
Please set the `spring.sleuth.sampler.probability=1.0`

**Comment by jichu20** [comment]
sorry I have these two properties
```yml
spring:
  sleuth:
    sampler:
      probability: 1.0
      percentage: 1.0
```

but not work

**Comment by marcingrzejszczak** [comment]
Can you please answer all the required questions described in the issue template? For your convenience let me paste it here

> **Describe the bug**
> Please provide details of the problem, including the version of Spring Cloud that you
are using. 
> 
> **Sample**
> If possible, please provide a test case or sample application that reproduces
the problem. This makes it much easier for us to diagnose the problem and to verify that
we have fixed it.

Can you provide a [complete, minimal, verifiable sample](https://stackoverflow.com/help/mcve) that reproduces the problem rather than pasted code? It should be available as a GitHub (or similar) project or attached to this issue as a zip file.

**Comment by jichu20** [comment]
Hi.

First of all, sorry for the little information.

In our organization we have a component in charge of sending the traces and the span to a tool similar to zipkin, collecting the information from the sysout.

We in our application have mounted sleuth + logback to propagate TraceId and SpanId headers and generate logs / traces with the necessary information for our component to send the information to our `zipkin`.

Now we want to generate traces with another format and another content. The content of the span. For this we have included zipkin in our application (I don't know if it is the correct thing to do) in order to generate a 'sender' that does not send anything to zipkin and that simply writes the information in the sysout.

To begin this task, we have included zipkin by default with the following settings:

```yml
spring:
  application:
    name: poc-logger
  zipkin:
    enabled: true
    baseUrl: https://webhook.site/1f66b8f8-d524-4a61-9ef9-b481b3cd53da
    sender:
      type: web
  sleuth:
    sampler:
      probability: 1.0
      percentage: 1.0
```

But we couldn't get any calls made.

Since we have the following filter, we think that for this reason zipkin calls are not being generated, but we are not sure.

```java
@Override
    public void doFilter(ServletRequest request, ServletResponse response, FilterChain chain) throws IOException, ServletException {
        Span currentSpan = this.tracer.currentSpan();
        if (currentSpan == null) {
            chain.doFilter(request, response);
            return;
        }

        String xTraceId = ((HttpServletRequest) request).getHeader("X-Rho-Traceid");

        if (StringUtils.isEmpty(xTraceId)) {
            xTraceId = UUID.randomUUID().toString();
            ExtraFieldPropagation.set(currentSpan.context(), "X-Rho-Traceid", xTraceId);
        }
        ((HttpServletResponse) response).addHeader("X-Rho-Traceid", xTraceId);

        MDC.put("X-Rho-Traceid", xTraceId);

        chain.doFilter(request, response);
    }
```

The version of spring cloud that we use is Hoxton.SR8 

I hope you can help us to write the information of the span in the sysout instead of sending it via web or to rabitmq
