### ISSUE TITLE
RabbitMQ Tracing Informations are missing

### ISSUE THREAD

**Issue by jmecsei** [spring-cloud/spring-cloud-sleuth#1822]
**Describe the bug**
I want to use a sleuth with RabbitMQ messaging, but I can't see the tracing informations. I generated a demo application with spring start, and add some minimal functionality, to produce a message to rabbitmq.

**Sample**
Here are the dependencies 
```xml

    <properties>
        <java.version>15</java.version>
        <spring-cloud.version>2020.0.0</spring-cloud.version>
    </properties>

    <dependencies>
        <dependency>
            <groupId>org.springframework.boot</groupId>
            <artifactId>spring-boot-starter-amqp</artifactId>
        </dependency>
        <dependency>
            <groupId>org.springframework.cloud</groupId>
            <artifactId>spring-cloud-starter-sleuth</artifactId>
        </dependency>
        <dependency>
            <groupId>org.springframework.cloud</groupId>
            <artifactId>spring-cloud-stream</artifactId>
        </dependency>
        <dependency>
            <groupId>org.springframework.cloud</groupId>
            <artifactId>spring-cloud-stream-binder-rabbit</artifactId>
        </dependency>

    <dependencyManagement>
        <dependencies>
            <dependency>
                <groupId>org.springframework.cloud</groupId>
                <artifactId>spring-cloud-dependencies</artifactId>
                <version>${spring-cloud.version}</version>
                <type>pom</type>
                <scope>import</scope>
            </dependency>
        </dependencies>
    </dependencyManagement>
```
application.yml
```yaml
spring:
  # Cloud Stream
  cloud:
    stream:
      rabbit.bindings:
        ipnMessageSupplier-out-0:
          producer:
            autoBindDlq: true
            bindingRoutingKey: simplepay
            routingKeyExpression: '''simplepay'''
      bindings:
        ipnMessageSupplier-out-0:
          destination: financial
          content-type: application/json
          producer.requiredGroups: simplepay.financial
    function:
      definition: ipnMessageSupplier

  # RabbitMQ
  rabbitmq:
    host: 127.0.0.1
    port: 5672
    username: root
    password: root
```

and the application java

```java
@SpringBootApplication
public class DemoApplication {

    public static void main(String[] args) {
        SpringApplication.run(DemoApplication.class, args);
    }

    @Bean
    Supplier<String> ipnMessageSupplier() {
        return () -> "DEMO";
    }
}
```
