### ISSUE TITLE
 SkipPatternConfiguration for actuator endpoint with WebFlux

### ISSUE THREAD

**Issue by oburgosm** [spring-cloud/spring-cloud-sleuth#1880]
An application with spring cloud 2020.0.1 and SB 2.4.2 using webflux. When I put next configuration, actuator spans are not skipped:

```
spring:
  webflux:
    base-path: /demo
management:
  server:
    port: 8081
    base-path: /demo
  endpoints:
    web:
      base-path: /actuator
```
