### ISSUE TITLE
logging.pattern.console override no longer works

### ISSUE THREAD

**Issue by bguedel** [spring-cloud/spring-cloud-sleuth#1893]
**Describe the bug**
> Please provide details of the problem, including the version of Spring Cloud that you
are using. 

In spring 2.3.x we set a custom logging pattern due to a line break issue. Normally we just use the default spring logging pattern, with the custom line break code. Sleuth 2.x was cool with this, and just overwrites `LOG_LEVEL_PATTERN`

Moving to spring 2.4.4 sleuth is updated to 3.x and the pattern no longer works.

**Sample**
> If possible, please provide a test case or a minimal sample **Java** application that reproduces
the problem. This makes it much easier for us to diagnose the problem and to verify that
we have fixed it.

Spring Boot version 2.4.4
Spring Cloud Dependencies 2020.0.2
  org.springframework.cloud:spring-cloud-starter-sleuth -> 3.0.2

```yaml
logging:
  level:
    root: WARN
  pattern:
    console: "${CONSOLE_LOG_PATTERN:%clr(%d{${LOG_DATEFORMAT_PATTERN:yyyy-MM-dd HH:mm:ss.SSS}}){faint} %clr(${LOG_LEVEL_PATTERN:%5p}) %clr(${PID: }){magenta} %clr(---){faint} %clr([%15.15t]){faint} %clr(%-40.40logger{39}){cyan} %clr(:){faint} %m%replace(%xException){'\n','\u2028'}%nopex%n}"
```

Removing the console pattern resolves it back to working.

**Comment by jonatan-ivanov** [comment]
I'm not sure if your pattern is correct, in logback config the default value comes after `:-` not `:`, could you please try out what happens if you put [this](https://github.com/spring-projects/spring-boot/blob/72a1eb6384bc5ca9171e0433dc6a3bb750c8e8b0/spring-boot-project/spring-boot/src/main/resources/org/springframework/boot/logging/logback/defaults.xml#L12) into your `logback-spring.xml` as the [documentation suggests](https://docs.spring.io/spring-cloud-sleuth/docs/current/reference/htmlsingle/#features-log-integration-json-logback)?

**Comment by marcingrzejszczak** [comment]
In which file do you set this configuration?

**Comment by bguedel** [comment]
src/main/resources/application.yml
```yml
spring:
  application:
    name: test-server

logging:
  pattern:
    console: "${CONSOLE_LOG_PATTERN:%clr(%d{${LOG_DATEFORMAT_PATTERN:yyyy-MM-dd HH:mm:ss.SSS}}){faint} %clr(${LOG_LEVEL_PATTERN:%5p}) %clr(${PID: }){magenta} %clr(---){faint} %clr([%15.15t]){faint} %clr(%-40.40logger{39}){cyan} %clr(:){faint} %m%replace(%xException){'\n','\u2028'}%nopex%n}"
```
output
```sh
2021-04-02 08:54:30.803  INFO 6996 --- [  restartedMain] c.d.bguedel.test.TestServerApplication   : Started TestServerApplication in 4.011 seconds (JVM running for 4.444)
```
---
```yml
spring:
  application:
    name: test-server

# logging:
#   pattern:
#     console: "${CONSOLE_LOG_PATTERN:%clr(%d{${LOG_DATEFORMAT_PATTERN:yyyy-MM-dd HH:mm:ss.SSS}}){faint} %clr(${LOG_LEVEL_PATTERN:%5p}) %clr(${PID: }){magenta} %clr(---){faint} %clr([%15.15t]){faint} %clr(%-40.40logger{39}){cyan} %clr(:){faint} %m%replace(%xException){'\n','\u2028'}%nopex%n}"
```

output
```sh
2021-04-02 08:54:48.992  INFO [test-server,,] 7263 --- [  restartedMain] c.d.bguedel.test.TestServerApplication   : Started TestServerApplication in 4.278 seconds (JVM running for 4.806)
```

**Comment by bguedel** [comment]
```yml
spring:
  application:
    name: test-server

logging:
  pattern:
    console: "${CONSOLE_LOG_PATTERN:-%clr(%d{${LOG_DATEFORMAT_PATTERN:-yyyy-MM-dd HH:mm:ss.SSS}}){faint} %clr(${LOG_LEVEL_PATTERN:-%5p}) %clr(${PID:- }){magenta} %clr(---){faint} %clr([%15.15t]){faint} %clr(%-40.40logger{39}){cyan} %clr(:){faint} %m%replace(%xException){'\n','\u2028'}%nopex%n}"
```

output
```sh
--2021-04-02 09:03:01.635 - INFO 8028 --- [  restartedMain] c.d.bguedel.test.TestServerApplication   : Started TestServerApplication in 4.164 seconds (JVM running for 4.632)
```
