### ISSUE TITLE
Customize log in Spring Cloud Sleuth

### ISSUE THREAD

**Issue by fightnyy** [spring-cloud/spring-cloud-sleuth#2112]
First of all, Thanks for your amazing work! You've created a great log system for variance tracking. 
But I have a question, even if I look at[ #1539](https://github.com/spring-cloud/spring-cloud-sleuth/issues/1539), https://github.com/spring-cloud/spring-cloud-sleuth/issues/1543 and #[1654](https://github.com/spring-cloud/spring-cloud-sleuth/issues/1654), I couldn't add the field part of Spring Cloud Sleuth Log at all. No matter what I did, only the form [AppName, TraceId, SpanId, exportable] came out. I 
* set spring.sleuth.log.slf4j.whitelisted-mdc-keys
* set baggage-keys
* set Span tag
* set ExtraFieldPropagation.set

 For better understanding I make this [repository](https://github.com/fightnyy/Spring-Cloud-Sleuth-Example), . In the end, this is what I want to do. [AppName, TraceId, SpanId, UserId (here UserId is added at controller), exportable)]
```
2022-02-07 17:57:23.570  INFO [service2(AppName),eca3f633d8f64037(TraceId),eca3f633d8f64037(SpanId), 5L(UserId), true] 82174 --- [nio-8082-exec-5] ... 
() parentheses is for better understanding
```
I've been doing it for about five days, but I still have no idea. I'd appreciate it if you helped me.

**Comment by marcingrzejszczak** [comment]
You have set that you want to use Cloud release train version 2021.0.0, that's great.

Then you explicitly define an ancient, incompatible version of Sleuth `org.springframework.cloud:spring-cloud-starter-sleuth:2.2.8.RELEASE`. 

You can check the PR to see all the changes necessary to fix your problem https://github.com/fightnyy/Spring-Cloud-Sleuth-Example/pull/1

IN general you need to override the default config as follows

```java
    // We want to control the way baggage fields are being set
    @Bean
    CorrelationScopeCustomizer mdcOverridingScopeCustomizer() {
        return builder -> {
            // We can't override [key] to flush on update so we need to remove the current entries
            builder.clear();
            // We're adding back the default ones related to tracing context
            builder.add(CorrelationScopeConfig.SingleCorrelationField.create(BaggageFields.TRACE_ID));
            builder.add(CorrelationScopeConfig.SingleCorrelationField.create(BaggageFields.SPAN_ID));
            builder.add(CorrelationScopeConfig.SingleCorrelationField.create(BaggageFields.SAMPLED));
            // We're setting the [key] baggage to flush on update
            builder.add(CorrelationScopeConfig.SingleCorrelationField
                    .newBuilder(BaggageField.create("key"))
                    .flushOnUpdate()
                    .build());

        };
    }
```

Properties

.application.yml
```yml
server.port: 8080

spring:
  application:
    name: LogTest
  sleuth:
    baggage-keys:
      - baggage
      - key
    log.slf4j.whitelisted-mdc-keys:
      - key

logging.level.org.springframework.cloud.sleuth: DEBUG

# bootstrap.yml is not necessary anymore
logging.pattern.level: "%5p [${spring.zipkin.service.name:${spring.application.name:}},%X{traceId:-},%X{spanId:-},%X{sampled:-},%X{key:-}]"

```

**Comment by fightnyy** [comment]
Thank you so much for responding so kindly. I'm really touched. @marcingrzejszczak 
Is it ok to ask you one more question? I saw your pr and then I found that if I want to add more field in Log what I have to do is (If I want to add `special` field in log)

`application.yml`
```
spring:
  application:
    name: LogTest
  sleuth:
    baggage-keys:
      - baggage
      - key
      - special
    log.slf4j.whitelisted-mdc-keys:
      - key
      - special
```
Config.java
```
 @Bean
    RestTemplate restTemplate() {
        return new RestTemplate();
    }

    // We want to control the way baggage fields are being set
    @Bean
    CorrelationScopeCustomizer mdcOverridingScopeCustomizer() {
        return builder -> {
            // We can't override [key] to flush on update so we need to remove the current entries
            builder.clear();
            // We're adding back the default ones related to tracing context
            builder.add(CorrelationScopeConfig.SingleCorrelationField.create(BaggageFields.TRACE_ID));
            builder.add(CorrelationScopeConfig.SingleCorrelationField.create(BaggageFields.SPAN_ID));
            builder.add(CorrelationScopeConfig.SingleCorrelationField.create(BaggageFields.SAMPLED));
            // We're setting the [key] baggage to flush on update
            builder.add(CorrelationScopeConfig.SingleCorrelationField
                            .newBuilder(BaggageField.create("hello"))
                            .flushOnUpdate()
                            .build());
            builder.add(CorrelationScopeConfig.SingleCorrelationField
                            .newBuilder(BaggageField.create("special"))
                            .flushOnUpdate()
                            .build());

        };
    }
```
But I still confusing what does `baggage` do in `spring.sleuth.baggage-keys`?
Do I have to put this in mandatory for it to work?
