### ISSUE TITLE
sleuth collect message from eureka server,which the zipkin ui show many urls-'/eureka/apps' that is invalid to me.

### ISSUE THREAD

**Issue by Layfolk-zcy** [spring-cloud/spring-cloud-sleuth#2231]
sleuth-3.1.1
spring-cloud-dependencies.version>2021.0.1
spring-cloud-alibaba-dependencies.version>2021.0.1.0
springBoot>2.6.3

**i want close urls that eureka server produce urls-like '/eureka/apps/..'**

**i try to add some configuration in eureka server, but the eureka server awalys report span-http.path is '/eurake/apps/...'.** For example:
```yaml
spring:
  sleuth:
    web:
      additional-skip-pattern: "/eureka/apps/*|/eureka/apps/|/eureka/*|/v2/api-docs/*|/v2/api-docs"
```
