### ISSUE TITLE
Not seeing traces in Zipkin Web UI

### ISSUE THREAD

**Issue by shyamjumberi** [spring-cloud/spring-cloud-sleuth#228]
Hi ,

Iam able to see the traces in console but not in the Zipkin web ui and running the "spring-cloud-sleuth-sample-zipkin" application.Could you please help me on this.

application.yml file
-----------------------
server:
  port: 3380

spring:
  application:
    # This ends up as the service name in zipkin
    name: testsleuthzipkin
  zipkin:
    # Uncomment to send to zipkin, replacing 192.168.99.100 with your zipkin IP address
     baseUrl: http://192.168.99.100:9411/
  sleuth:
    sampler:
      percentage: 1.0

sample:
  zipkin:
    # When enabled=false, traces log to the console. Comment to send to zipkin
    #enabled: false

**Comment by marcingrzejszczak** [comment]
Can you post your sample app somewhere? Without it it will be difficult to help you

**Comment by shyamjumberi** [comment]
Hi ,
I have committed the code into below path.
https://github.com/shyamjumberi/SpringSleuthZipkin.git

Please let me know if any information required.

**Comment by marcingrzejszczak** [comment]
Which OS do you use? What's the host of your docker-machine?

**Comment by shyamjumberi** [comment]
Iam using window 7 professional and installed the docker. 
Docker host is 192.168.99.100

**Comment by marcingrzejszczak** [comment]
Your docker-compose is wrong. It tried to connect to Mysql DB to `localhost`. However it's in a separate container. Change your docker-compose to the following at it will work like a charm:

```
mysql:
  image: openzipkin/zipkin-mysql:1.38.1
  ports:
    - 3306:3306
query:
  image: openzipkin/zipkin-java:0.9.3
  environment:
    - TRANSPORT_TYPE=http
    - STORAGE_TYPE=mysql
  ports:
    # Historical port used for the Zipkin HTTP Api
    - 9411:9411
    # Zipkin UI used to be on a separate process listening on port 8080
    - 8080:9411
  links:
    - mysql:storage
```
