### ISSUE TITLE
scs-binder-kafka with sc-sleuth-stream does not continue span across topics

### ISSUE THREAD

**Issue by donovanmuller** [spring-cloud/spring-cloud-sleuth#282]
Using `spring-cloud-stream-binder-kafka` with `spring-cloud-sleuth-stream` (Brixton release versions) in two test apps (test-app-1 and test-app-2), sending a message on the `hello` topic and publishing spans to a Zipkin collector:

`pom.xml` (test-app-1 and test-app-2)
```
<?xml version="1.0" encoding="UTF-8"?>
<project xmlns="http://maven.apache.org/POM/4.0.0"
         xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
         xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 http://maven.apache.org/xsd/maven-4.0.0.xsd">
    <modelVersion>4.0.0</modelVersion>

    <groupId>example</groupId>
    <artifactId>test-app-1/2</artifactId>
    <version>1.0-SNAPSHOT</version>

    <dependencies>
        ...
        <!-- See: https://github.com/spring-cloud/spring-cloud-sleuth/issues/281 -->
        <dependency>
            <groupId>org.springframework.boot</groupId>
            <artifactId>spring-boot-starter-aop</artifactId>
        </dependency>
        <dependency>
            <groupId>org.springframework.cloud</groupId>
            <artifactId>spring-cloud-sleuth-stream</artifactId>
        </dependency>
        <dependency>
            <groupId>org.springframework.cloud</groupId>
            <artifactId>spring-cloud-stream-binder-kafka</artifactId>
        </dependency>
        ...
```

using the following config:

`application.yml` (test-app-1)
```
spring:
  application:
    name: ${project.artifactId}
  cloud:
    stream:
      bindings:
        output:
          destination: hello
      kafka:
        binder:
          zkNodes: kafka
          brokers: kafka
```

`application.yml` (test-app-2)
```
spring:
  application:
    name: ${project.artifactId}
  cloud:
    stream:
      bindings:
        input:
          destination: hello
      kafka:
        binder:
          zkNodes: kafka
          brokers: kafka
```

with test-app-1 sending the message with:

```
@RestController
@EnableBinding(Source.class)
public class HelloResource {

    private static final Logger log = LoggerFactory.getLogger(HelloResource.class);

    private Source source;

    @Autowired
    public HelloResource(final Source source) {
        this.source = source;
    }

    @RequestMapping("/hello")
    public void hello() {
        source.output().send(MessageBuilder.withPayload("Hello!").build());
        log.debug("Said hello");
    }
}
```

and test-app-2 receiving the message like so:

```
@EnableBinding(Sink.class)
public class HelloSink {

    private static final Logger log = LoggerFactory.getLogger(TestSink.class);

    @ServiceActivator(inputChannel = Sink.INPUT)
    public void helloHole(GenericMessage message) {
        log.debug("Message: {}", message);
    }
}
```

The above will result in test-app-1 logging:

```
2016-05-22 22:26:52.861 DEBUG [test-app-1,b362b90bceac21b3,b362b90bceac21b3,true] 89048 --- [nio-8082-exec-2] example.HelloResource               : Said hello
```

and test-app-2 logging:

```
2016-05-22 22:38:17.759 DEBUG [test-app-2,8326ed3be5ce67df,8326ed3be5ce67df,true] 89106 --- [  kafka-binder-] example.HelloSink                      : Message: GenericMessage [payload=Hello!, headers={kafka_topic=hello, kafka_nextOffset=37, X-Message-Sent=true, kafka_offset=36, X-Span-Name=message:input, kafka_messageKey=null, X-B3-SpanId=8326ed3be5ce67df, X-B3-Sampled=1, kafka_partitionId=0, X-B3-TraceId=8326ed3be5ce67df, id=40a0a41a-d687-4487-cf55-32ea0e051efc, X-Current-Span=[Trace: 8326ed3be5ce67df, Span: 8326ed3be5ce67df, exportable=true], contentType=text/plain, timestamp=1463949497759}]
```

note that test-app-2 has generated a _new_ trace/span instead of using the parent trace started by test-app-1. Testing with `spring-cloud-stream-binder-rabbit` works as expected, with the parent trace being continued.

After some digging it basically comes down to how `Message` headers are embedded for Kafka.
In [`KafkaMessageChannelBinder#handleMessageInternal `](https://github.com/spring-cloud/spring-cloud-stream/blob/v1.0.0.RELEASE/spring-cloud-stream-binders/spring-cloud-stream-binder-kafka/src/main/java/org/springframework/cloud/stream/binder/kafka/KafkaMessageChannelBinder.java#L855) and using the default `HeaderMode.embeddedHeaders`, the original headers, including the Sleuth trace/span headers are [thrown away](https://github.com/spring-cloud/spring-cloud-stream/blob/v1.0.0.RELEASE/spring-cloud-stream/src/main/java/org/springframework/cloud/stream/binder/EmbeddedHeadersMessageConverter.java#L56) and only the [`BinderHeaders.STANDARD_HEADERS`](https://github.com/spring-cloud/spring-cloud-stream/blob/v1.0.0.RELEASE/spring-cloud-stream-binders/spring-cloud-stream-binder-kafka/src/main/java/org/springframework/cloud/stream/binder/kafka/KafkaMessageChannelBinder.java#L186) are embedded.

The workaround is to explicitly add the Sleuth headers (taken from [`MessagingSpanExtractor#joinTrace`](https://github.com/spring-cloud/spring-cloud-sleuth/blob/48f3f9783f277a795d0210399f0ea09b7f1a4e71/spring-cloud-sleuth-core/src/main/java/org/springframework/cloud/sleuth/instrument/messaging/MessagingSpanExtractor.java#L41)) in `spring.cloud.stream.kafka.binder.headers`:

```
spring:
  ...
  cloud:
    stream:
      ...
      kafka:
        binder:
           headers:
             - X-B3-TraceId
             - X-B3-SpanId
             - X-B3-Sampled
             - X-B3-ParentSpanId
             - X-Span-Name
             - X-Process-Id
          zkNodes: kafka
          brokers: kafka
```

and then the trace gets continued as the headers are there to get the parent trace in [`TraceChannelInterceptor#preSend`](https://github.com/spring-cloud/spring-cloud-sleuth/blob/v1.0.0.RELEASE/spring-cloud-sleuth-core/src/main/java/org/springframework/cloud/sleuth/instrument/messaging/TraceChannelInterceptor.java#L74)

If the explicit Kafka Sleuth header configuration is intended then it should be documented.
Otherwise, I guess the Sleuth headers should be preserved somehow when embedding the headers for Kafka.
