### ISSUE TITLE
Failed to initialize pool: Could not connect to address=(host=localhost)(port=3306)(type=master) 

### ISSUE THREAD

**Issue by Dreampie** [spring-cloud/spring-cloud-sleuth#422]
```
server:
  port: 9411

spring:
  datasource:
    schema: classpath:/mysql.sql
    url: ${DATASOURCE_URL:jdbc:mysql://mysql.infra.xx.com:3306/cloud_zipkin?useSSL=false&autoReconnect=true&characterEncoding=utf-8}
    username: ${DATASOURCE_USERNAME:xx}
    password: ${DATASOURCE_PASSWORD:xx}
    maxIdle: 300
    maxActive: 600
    maxWait: 1000
    testOnBorrow: true
    validationQuery: SELECT 1
    initialize: true
    continueOnError: true
  sleuth:
    enabled: false

zipkin:
  storage:
    type: mysql # default is mem (in-memory) / mysql
```

```
ERROR: cannot load span names: Request processing failed; nested exception is com.zaxxer.hikari.pool.HikariPool$PoolInitializationException: Failed to initialize pool: Could not connect to address=(host=localhost)(port=3306)(type=master) : Connection refused
Service Name

```
