### ISSUE TITLE
spring.sleuth.web.client.enabled setting to false causes application not to start

### ISSUE THREAD

**Issue by altfatterz** [spring-cloud/spring-cloud-sleuth#433]
I have the following configuration:

```
spring:
  application:
    name: foo-service
  sleuth:
    sampler:
      # by default 10% of requests are sampled, here we say sample all requests
      percentage: 1.0
    web:
      enabled: true
      client:
        enabled: false
```

Starting the application:

```
***************************
APPLICATION FAILED TO START
***************************

Description:

Parameter 5 of method traceWebFilter in org.springframework.cloud.sleuth.instrument.web.TraceWebAutoConfiguration required a bean of type 'org.springframework.cloud.sleuth.instrument.web.HttpTraceKeysInjector' that could not be found.
    - Bean method 'httpTraceKeysInjector' not loaded because @ConditionalOnProperty (spring.sleuth.web.client.enabled) found different value in property 'spring.sleuth.web.client.enabled'


Action:

Consider revisiting the conditions above or defining a bean of type 'org.springframework.cloud.sleuth.instrument.web.HttpTraceKeysInjector' in your configuration.

```

According to the http://cloud.spring.io/spring-cloud-static/spring-cloud-sleuth/1.0.10.RELEASE/#_http_client_integration this is not expected.

I am using `1.0.10.RELEASE` version
