### ISSUE TITLE
Sleuth-Zipkin: If Sleuth is disabled Zipkin is still enabled and produces an exception due to a missing bean.

### ISSUE THREAD

**Issue by FlorianLautenschlager** [spring-cloud/spring-cloud-sleuth#600]
With Spring Boot 1.5.2 and Spring-Cloud-Sleuth-* 1.2.1 an exception is produced by the following two bad configuration values.

Bad Configuration 1:
```YAML
spring:
  sleuth:
    enabled: true
```

Bad Configuration 2:
```YAML
spring:
  sleuth:
    enabled: false
  zipkin:
   enabled: true
```
The problem is, that if `spring.zipkin.enabled` is `true` Spring Boot loads the configuration (`ZipkinAutoConfiguration.java`) that tries to create the Bean 

```JAVA
@Bean
public SpanReporter zipkinSpanListener(ZipkinSpanReporter reporter, EndpointLocator endpointLocator, Environment environment, List<SpanAdjuster> spanAdjusters) {
 return new ZipkinSpanListener(reporter, endpointLocator, environment, spanAdjusters);
}
```
But the `SpanAdjuster` is created in the `TraceAutoConfiguration.java` that is not loaded because of `spring.sleuth.enabled: false`

Good Configuration 1:
```YAML
spring:
  sleuth:
    enabled: false
  zipkin:
    enabled: false
```

Good Configuration 2:
```YAML
spring:
  sleuth:
    enabled: true
  zipkin:
    enabled: false
```

Environment:
 - Spring Boot 1.5.2
 - Sleuth-* 1.2.1

Reproducer: https://github.com/FlorianLautenschlager/spring.sleuth
