### ISSUE TITLE
'X-B3-TraceId' header value is duplicated in the access log

### ISSUE THREAD

**Issue by shaunthomas999** [spring-cloud/spring-cloud-sleuth#795]
Hi,

I am using spring-cloud to setup a microservice architecture where http calls are routed through api-gateway to experience API microservices (xp-api) and to capability API microservice (c-api):

api-gatway -> xp-api -> c-api

Netflix Zuul is used for routing & filtering and sleuth is enabled for tracing.

I want to print 'X-B3-TraceId' in the access log for which I am using following properties in application.yml file.

```
server:
  maxHttpHeaderSize: 65536
  tomcat:
    basedir:
    accesslog:
      enabled: true
      prefix: access
      pattern: '%h %t "%r" %s %b %D "%{Referer}i" "%{User-agent}i" "%{X-B3-TraceId}i"'
```

In the xp-api access logs, the value of 'X-B3-TraceId' header is duplicated. For e.g. `"0ff6b1beb3245e03,0ff6b1beb3245e03"`. While in c-api, the value appear only once. For e.g. `"0ff6b1beb3245e03"`. 

How can we avoid having duplicate values for 'X-B3-TraceId' header in xp-api?
