### ISSUE TITLE
meet 'zipkin.storage.type=mysql' found different value when using elasticsearch 

### ISSUE THREAD

**Issue by soulrenger** [spring-cloud/spring-cloud-sleuth#922]
Hi,
   I'm trying to use ES to store those messages,and I just met the following exception :
```
***************************
APPLICATION FAILED TO START
***************************

Description:

Parameter 0 of constructor in zipkin.server.ZipkinHttpCollector required a bean of type 'zipkin.storage.StorageComponent' that could not be found.
	- Bean method 'storage' not loaded because @ConditionalOnProperty (zipkin.storage.type=mysql) found different value in property 'zipkin.storage.type'


Action:

Consider revisiting the conditions above or defining a bean of type 'zipkin.storage.StorageComponent' in your configuration.


Process finished with exit code 1

```

## This is my `pom.xml`

```
<?xml version="1.0" encoding="UTF-8"?>
<project xmlns="http://maven.apache.org/POM/4.0.0" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
         xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 http://maven.apache.org/xsd/maven-4.0.0.xsd">
    <modelVersion>4.0.0</modelVersion>

    <groupId>com.hulu.example</groupId>
    <artifactId>zipkin</artifactId>
    <version>0.0.1-SNAPSHOT</version>
    <packaging>jar</packaging>

    <name>zipkin</name>
    <description>Demo project for Spring Boot</description>

    <parent>
        <groupId>org.springframework.boot</groupId>
        <artifactId>spring-boot-starter-parent</artifactId>
        <version>1.5.10.RELEASE</version>
        <relativePath/> <!-- lookup parent from repository -->
    </parent>

    <properties>
        <project.build.sourceEncoding>UTF-8</project.build.sourceEncoding>
        <project.reporting.outputEncoding>UTF-8</project.reporting.outputEncoding>
        <java.version>1.8</java.version>
        <spring-cloud.version>Edgware.SR3</spring-cloud.version>
    </properties>

    <dependencies>
        <dependency>
            <groupId>org.springframework.cloud</groupId>
            <artifactId>spring-cloud-sleuth-dependencies</artifactId>
            <type>pom</type>
            <scope>import</scope>
        </dependency>

        <dependency>
            <groupId>org.springframework.cloud</groupId>
            <artifactId>spring-cloud-starter-eureka</artifactId>
        </dependency>
        <dependency>
            <groupId>org.springframework.cloud</groupId>
            <artifactId>spring-cloud-sleuth-zipkin-stream</artifactId>
        </dependency>
        <dependency>
            <groupId>org.springframework.cloud</groupId>
            <artifactId>spring-cloud-starter-stream-rabbit</artifactId>
        </dependency>
        <dependency>
            <groupId>io.zipkin.java</groupId>
            <artifactId>zipkin-autoconfigure-ui</artifactId>
        </dependency>
        <dependency>
            <groupId>org.springframework.boot</groupId>
            <artifactId>spring-boot-starter-test</artifactId>
            <scope>test</scope>
        </dependency>
        <dependency>
            <groupId>io.zipkin.java</groupId>
            <artifactId>zipkin</artifactId>
        </dependency>
        <!-- add the dependency for elasticsearch via http -->
        <dependency>
            <groupId>io.zipkin.java</groupId>
            <artifactId>zipkin-autoconfigure-storage-elasticsearch-http</artifactId>
            <optional>true</optional>
        </dependency>

    </dependencies>

    <dependencyManagement>
        <dependencies>
            <dependency>
                <groupId>org.springframework.cloud</groupId>
                <artifactId>spring-cloud-dependencies</artifactId>
                <version>${spring-cloud.version}</version>
                <type>pom</type>
                <scope>import</scope>
            </dependency>
        </dependencies>
    </dependencyManagement>

    <build>
        <plugins>
            <plugin>
                <groupId>org.springframework.boot</groupId>
                <artifactId>spring-boot-maven-plugin</artifactId>
            </plugin>
        </plugins>
    </build>
</project>
```

and this my `application.yml`

```
eureka:
  client:
    service-url:
      defaultZone:http://192.168.1.100:8761/eureka/
server:
  port: 9411
spring:
  application:
    name: zipkin-server
  sleuth:
    sampler:
      percentage: 1.0
      enabled: false
  rabbitmq:
    host: localhost
    port: 5672
    username: guest
    password: guest
zipkin:
  storage:
    StorageComponent: elasticsearch
    type: elasticsearch
    elasticsearch:
      cluster: elasticsearch
      max-requests: 30
      index: zipkin
      index-shards: 3
      index-replicas: 1
      hosts: http://192.168.1.100:9200
```
I have looked up a lot of webpages and they shows `zipkin.storage.type=elasticsearch` is valid configuration
